leia = input("Digite algo: ")
print("O tipo primitivo desse valor é:", type(leia))
print("Só tem espaços?", leia.isspace())
print("É um número?", leia.isnumeric())
print("É alfabético?", leia.isalpha())
print("É alfanumérico?", leia.isalnum())
print("Está em letras maiúsculas?", leia.isupper())
print("Está em letras minúsculas?", leia.islower())
print("Está capitalizada?", leia.istitle())
